version: '3'
services:
  web:
    image: sixlive/core-php-web
    ports:
      - ${DOCKER_WEB_PORT}:80

  mysql:
    image: mysql:5.7
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
